spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filter:
        -
      routes:
        - id: course-service-route
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: subscripcion-service-route
          uri: lb://subscripcion-service
          predicates:
            - Path=/subscription/**

server:
  port: ${SERVER_PORT:8012}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'